theme: minima
title : Chad Baldwin

author:
  name: Chad Baldwin
#  email:

minima:
  social_links:
    twitter: chad_baldwin
    github: chadbaldwin
    stackoverflow: "3474677"
    linkedin: chadbaldwin
