theme: minima

title: Chad's Blog
author: Chad Baldwin
email: blog@chadbaldwin.net
url: https://chadbaldwin.net

description: >
  My first blog. Probably no one else will ever read it, but oh well.

twitter_username:  chad_baldwin
github_username:   chadbaldwin
linkedin_username: chadbaldwin

# Used by simple links page
social-links:
  LinkedIn:      https://linkedin.com/in/chadbaldwin
  Twitter:       https://twitter.com/chad_baldwin
  Instagram:     https://instagram.com/chad_baldwin
  GitHub:        https://github.com/chadbaldwin
  StackOverflow: https://stackoverflow.com/users/3474677
  Reddit:        https://www.reddit.com/user/chadbaldwin
  Website:       http://chadbaldwin.net

# for SEO plugin
twitter:
  username: chad_baldwin
  card: summary_large_image
social:
  name: Chad Baldwin
  links:
    - https://twitter.com/chad_baldwin
    - https://www.linkedin.com/in/chadbaldwin
    - https://github.com/chadbaldwin

titles_from_headings:
  strip_title: true

header_pages:
  - resume.html
  - archive.md
  - books.md

plugins:
  - jekyll-sitemap

google_analytics: UA-185058308-1
gravatar_hash: 2136e716a089f4a3794f4007328c7bfb

# The github repo that is to be used for looking up comments
comments_repo: chadbaldwin/chadbaldwin.github.io

defaults:
  - scope:
      path: ""
    values:
      image: https://s.gravatar.com/avatar/2136e716a089f4a3794f4007328c7bfb?s=800

# highlighter: none # Not supported by GitHub Pages
kramdown:
    syntax_highlighter_opts:
      disable: true

# minima v3.0 - uses new yaml schema for social
minima:
  social_links:
    twitter: chad_baldwin
    github: chadbaldwin
    stackoverflow: "3474677"
    instagram: chad_baldwin
    linkedin: chadbaldwin
#   youtube: jekyll
    youtube_channel: UC1xIzejSoxhymEJxGhncRGQ
    youtube_channel_name: Chad Baldwin

######################
####### Resume #######
######################
resume:
  theme: default
  header:
    name: Chad Baldwin
    display_contact_info: true
    current_title: Database Developer
    looking_for_work: true
    intro: >
      As a motivated and versatile software developer, I love taking on any project I can,
      large or small, I don't shy away from a challenge. Experienced in building and working
      with complex SQL Server ecosystems. I regularly keep up to date with all of the latest updates,
      changes, tools and best practices. I work well in both team and independent environments.
  contact:
    #address: 123 Main St, Test, CA 91234
    #phone: (123) 456-7890
    email: blog@chadbaldwin.net
  sections:
    experience:   true
    education:    true
    projects:     true
    skills:       true
    recognition:  true
    associations: false
    interests:    false
    links:        false
    social_links: false
  social:
    Website:    http://chadbaldwin.net
    GitHub:     https://github.com/chadbaldwin
    Twitter:    https://twitter.com/chad_baldwin
    #Dribbble:  https://dribbble.com/chadbaldwin
    #FaceBook:  https://facebook.com/iamchadbaldwin
    LinkedIn:   https://linkedin.com/in/chadbaldwin
    #Instagram: https://instagram.com/chad_baldwin
    #Medium:    https://medium.com/@chad-baldwin