theme: minima

title: Chad's Blog
author: Chad Baldwin
email: blog@chadbaldwin.net
url: https://chadbaldwin.net

description: >
  My first blog. Probably no one else will ever read it, but oh well.

twitter_username: chad_baldwin
github_username: chadbaldwin
linkedin_username: chadbaldwin

titles_from_headings:
  enabled: true
  strip_title: true

header_pages:
  - resume.md
#  - feed.xml # most people know to look for /feed on a blog to find the feed. Hiding it for now

plugins:
  - jekyll-feed

google_analytics: UA-185058308-1