theme: minima

title: Chads Blog
author: Chad Baldwin
email: blog@chadbaldwin.net

description: >
  My first blog. Probably no one else will ever read it, but oh well.

twitter_username: chad_baldwin
github_username: chadbaldwin
linkedin_username: chadbaldwin

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
highlighter: rouge
